### ISSUE TITLE
Problem with building query with Oracle as database

### ISSUE THREAD

**Issue by ekarlso** [spadefoot/kohana-orm-leap#13]
$b = DB_SQL::select()->from("DB_COPY");
$b->limit(5);
echo $b->statement();

This just gives:

SELECT \* FROM "DB_COPY";

Which is mostly useless.

**Comment by spadefoot** [comment]
I will add limit support for Oracle today in accordance with this article: http://www.oracle.com/technetwork/issue-archive/2006/06-sep/o56asktom-086197.html

**Comment by ekarlso** [comment]
When do you think that you will have this in place?

**Comment by spadefoot** [comment]
Just posted the code.  Please let me know how it works for you.
