### ISSUE TITLE
Oracle LIMIT and OFFSET $max_row_to_fetch problem

### ISSUE THREAD

**Issue by ekarlso** [spadefoot/kohana-orm-leap#15]
If you use this and set $select->offset(10) and then $select->limit(10) it will gives you 1 row to many ?!

string(238) "SELECT \* FROM (SELECT "t0".*, ROWNUM AS "rn" FROM (SELECT \* FROM "DB_COPY" ORDER BY "STATUS" ASC) "t0" WHERE ROWNUM <= 11) WHERE "rn" >= 1;
Total Pages: 72
Total Rows: 712
Requested Page: 1
Per Page:10
From Row: 1

**Comment by spadefoot** [comment]
Ok, I will commit a fix this evening.

**Comment by spadefoot** [comment]
I changed the "WHERE ROWNUM <= 11" to "WHERE ROWNUM < 11"....  Please let me know if you have any further issues with it.
