### ISSUE TITLE
Oracle - Add support for DATE formats when it's LONG and others

### ISSUE THREAD

**Issue by ekarlso** [spadefoot/kohana-orm-leap#16]
Oracle dates can be a bit fuzzy, can you look into doing a to_char on the FIELD ?

**Comment by spadefoot** [comment]
Absolutely, I will look into coming up with a solution for that issue.  If you have any code suggestions, please let me know and I can integrate them.  Can you post any examples (i.e. before and after)?

**Comment by spadefoot** [comment]
I just uploaded a new datetime field adaptor.  Let me know how that works for you.  I will post on the [Web site](http://orm.spadefootcode.com) the API information and add it to the [tutorials](http://orm.spadefootcode.com/tutorials/mapping-a-model/#adaptors) section.

**Comment by ekarlso** [comment]
Optimally you would make it so that it uses TO_CHAR in Oracle so you can do like: 
SELECT TO_CHAR (<daterow>, 'YYYY-MM-DD HH24:MI') FROM <table>

**Comment by spadefoot** [comment]
Try using either DB_SQL::expr($expr, Array $params) or DB_ORM::expr($expr, Array $params).
