### ISSUE TITLE
Add support for case insensitive searching

### ISSUE THREAD

**Issue by ekarlso** [spadefoot/kohana-orm-leap#19]
Is there a possibility to add support for case insensitive searching in the ORM ? 

Oracle uses SELECT \* FROM <table> WHERE UPPER(<column>) LIKE <pattern>;

Or you can do WHERE LOWER() ....

**Comment by ekarlso** [comment]
Or do:
http://askanantha.blogspot.com/2007/07/making-oracle-case-insensitive.html

**Comment by spadefoot** [comment]
I believe you are looking for the following:

$results = DB_SQL::select('default')->from('table')->where(DB_SQL::expr("UPPER('value')"), '=', 'text')->query();

or

$results = DB_ORM::select('model')->where(DB_ORM::expr("UPPER('value')"), '=', 'text')->query();
