### ISSUE TITLE
Guide API unexpected T_CONSTANT_ENCAPSED_STRING, expecting T_CASE or T_DEFAULT or '}'

### ISSUE THREAD

**Issue by nyunyu95** [spadefoot/kohana-orm-leap#21]
Hello,

I'm getting an error while trying to user my API guide. I'm getting this error :

"ErrorException [ Parse Error ]: syntax error, unexpected T_CONSTANT_ENCAPSED_STRING, expecting T_CASE or T_DEFAULT or '}'
MODPATH/leap/classes/base/db/drizzle/schema.php [ 68 ]"

The problem seems to come from the switch() used on the line 67.

switch ($actual_type) {
    'blob'                      => array('type' => 'string', 'binary' => TRUE, 'character_maximum_length' => '65535'),
    .....,
}

Are you sure about what you've done there ? :p
I prefer to not try to fix your work. I could misunderstand it ! :)

Regards,

(I do not use drizzle or made any modifications on files)

**Comment by nyunyu95** [comment]
I just noticed (trying to remove the schema.php file, just "to see") that I'm getting the same errors every schema.php files

**Comment by spadefoot** [comment]
At the moment, the schema.php files are ALL still under development and unfortunately do not work....my apologizes.  I will look at speeding up their development here shortly.

As for the Drizzle connection, for some reason the drizzle functions seem to conflict with Kohana.  If you got any ideas on how to resolve this conflict, I would be happy to add your changes.  Otherwise, in the meantime, you can use the MySQL connections.

**Comment by nyunyu95** [comment]
Thanks for you quick anwser !

My problem is not in the "use" of Drizzle (or whatever) connection.
I can't access my API Guide (http://..../guide/api). All those schema.php files make that error appears.

I temporary fixed that problem by renaming the schema.php files that made this error appears but this is not a real solution !

**Comment by spadefoot** [comment]
Ok, I will comment out the code in those files so that such errors don't occur.  Thank you for pointing out that issue!  I will do that tonight.

**Comment by nyunyu95** [comment]
Alright ! :)
Thanks for your care ! If I see anything else, I'll tell you :)

**Comment by spadefoot** [comment]
Just uploaded the commented out code.
