### ISSUE TITLE
Add a many-to-many relation.

### ISSUE THREAD

**Issue by ghost** [spadefoot/kohana-orm-leap#22]
It has been recommended that the [LEAP ORM](http://orm.spadefootcode.com) implement a many-to-many relation for handling such relationships.  This would be in addition to the currently supported [relations](http://orm.spadefootcode.com/tutorials/mapping-a-model/#relations).

**Comment by bluesnowman** [comment]
The ORM can now create a "has many through" relation by adding the following metadata to a "has many" relation definition:

```
$this->relations = array(
    ...
    'users_roles' => new DB_ORM_Relation_HasMany($this, array(
        'parent_key' => array('uID'),
        'through_model' => 'user_role',
        'through_keys' => array(
            array('uID'), // matches with parent
            array('rID'), // matches with child
        ),
        'child_model' => 'role',
        'child_key' => array('rID'),
    )),
    ...
);
```
