### ISSUE TITLE
Update code to use Kohana styling

### ISSUE THREAD

**Issue by ghost** [spadefoot/kohana-orm-leap#3]
I would also recommend reading the Kohana coding style guide, following these rules will help make your code easier for others to read.

**Comment by spadefoot** [comment]
Kohana's Conventions and Coding Style guide is located online at http://kohanaframework.org/3.2/guide/kohana/conventions.

**Comment by spadefoot** [comment]
The Leap ORM complies to the majority of these conventions and has a clean code base.  Any remaining style differences are minor.
