### ISSUE TITLE
Password  incorrectly spelled as 'Passoord'

### ISSUE THREAD

**Issue by Samnan** [spadefoot/kohana-orm-leap#32]
https://github.com/spadefoot/kohana-orm-leap/blob/3.2/master/classes/base/model/leap/user.php

Line 49 says: Passoord

Caused Auth to fail with exception. Please fix the typo :)

**Comment by bluesnowman** [comment]
Much appreciated.  We just added the auth module this past week so I am in the process of debugging it.  I will fix it immediately.  Please let me know if you find any others.

**Comment by bluesnowman** [comment]
I fixed the misspelled field name.  I will work on the other issue you also submitted here in a little bit.
