### ISSUE TITLE
unnecessary validate() function call inside DB_ORM_Field class'

### ISSUE THREAD

**Issue by taai** [spadefoot/kohana-orm-leap#50]
Why is the DB_ORM_Field's (all of them) `validate()` function getting called, if returned value isn't actually being used? Have look:
https://github.com/spadefoot/kohana-orm-leap/blob/3.2/master/classes/base/db/orm/field/integer.php#L87
and
https://github.com/spadefoot/kohana-orm-leap/blob/3.2/master/classes/base/db/orm/field.php#L114

The returned value isn't being used and it doesn't raise any exception (as at least I would expect) - so what's the point?!

**Comment by bluesnowman** [comment]
Great catch. I think this was a silly oversight.  It should be getting checked.  I will work on getting this fixed asap.

**Comment by taai** [comment]
Yep, now it's fixed. Thanks, Matthew!

**Comment by taai** [comment]
Bugs!

**ErrorException [ Recoverable Error ]: Argument 1 passed to Kohana_Validation_Exception::__construct() must be an instance of Validation, null given**

The first argument can't be NULL, it must be Validation. ;)

**Comment by taai** [comment]
And! Why can't I do like this?

``` php
<?php
$car->purchased = DB_SQL::expr('now()');
```

This gives me that Exception (the buggy one mentioned above).

Maybe this calls for refactoring, no?!
