### ISSUE TITLE
separate "create" and "update" functions instead of "save"

### ISSUE THREAD

**Issue by taai** [spadefoot/kohana-orm-leap#62]
It's great that there is the `save()` function that automatically understands what to do - create or update.
But it is not possible to create a new record, when providing also a primary key (id). For example, I would set the "id" manually - Leap would think that I'm willing to update, not create.

So, there needs to be a separate `create()` and `update()` functions, and the `save()` as a automatic save/update function caller.

**Comment by bluesnowman** [comment]
Yeah, this sound like a good idea.  I can definitely see a use for these functions.  I will see what we can do to make this happen.

**Comment by taai** [comment]
I have already written the code to make this happen. Actually I have done alot of modifications... It would be easyer for me to have a little chat so I can tell all about what I have done...
