### ISSUE TITLE
Handling of Decimal Fields are wrong!

### ISSUE THREAD

**Issue by ghost** [spadefoot/kohana-orm-leap#78]
Following Line

```
 $value = number_format( (float) $value, $this->metadata['scale']);
```

should be turned into this:

```
$value = number_format( (float) $value, $this->metadata['scale'], '.', '');
```

The first statement produces the following:

input value: 5000.38
number_format output: 5,000.38

next line (settype) produces then this: 5 (because the comma is not handled correctly!)

**Comment by bluesnowman** [comment]
Thanks!  Just updated it....
