### ISSUE TITLE
[Auth] Error when using the "remember" feature

### ISSUE THREAD

**Issue by nyunyu95** [spadefoot/kohana-orm-leap#81]
Hello guys,

Once more, thank you for your amazing job here !

I just figured out, I guess anyway, an error inside the Authentication system.

Here is my code :

<pre><code>
if ($post->check())
 {
    [...]
    Auth_Leap::instance()->login($uname, $pwd, $remember);
}</code></pre> 

and then i got the following error :

> ErrorException [ Strict ]: Declaration of Base_Model_Leap_User_Token::save() should be compatible with that of Base_DB_ORM_Model::save()

I've fixed that problem by changing the prototyping of the save() method in "/leap/classes/Base/Model/Leap/User/Token.php" from :

<pre><code>public function save($reload = FALSE) {</code></pre> 

to

<pre><code>public function save($reload = FALSE, $mode = NULL) {</code></pre>

I hope this is a good fix and I hope it will help other people.

Best Regards,

**Comment by bluesnowman** [comment]
Ok, I am fixing it right now.

**Comment by nyunyu95** [comment]
Sweet! I'd forgot to change the parent's call also ;) Thanks !
