### ISSUE TITLE
Not working examples in 3.3 

### ISSUE THREAD

**Issue by phpclub** [spadefoot/kohana-orm-leap#84]
http://orm.spadefootcode.com/tutorials/querying-sql-statements/

1) ErrorException [ Fatal Error ]: Class 'DB_Connection' not found
$connection = DB_Connection::factory('default');

2) $connection = DB_Connection_Pool::instance()->get_connection('default');
ErrorException [ Fatal Error ]: Class DB_SQL_Lock_Builder contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Base_DB_SQL_Lock_Builder::acquire, Base_DB_SQL_Lock_Builder::add, Base_DB_SQL_Lock_Builder::release)
MODPATH/leap/classes/DB/SQL/Lock/Builder.php [ 26 ]
21  *
22  \* @package Leap
23  \* @category DB2
24  \* @version 2013-01-11
25  */
26 class DB_SQL_Lock_Builder extends Base_DB_SQL_Lock_Builder {}

**Comment by bluesnowman** [comment]
Ok, I will get it working again ASAP.

**Comment by bluesnowman** [comment]
@phpclub Edit classes/DB/SQL/Lock/Builder.php.  Add the "abstract" keyword before the class declaration.  It should be:

```
abstract class DB_SQL_Lock_Builder extends Base_DB_SQL_Lock_Builder {}
```

I will update it in the repository.

**Comment by phpclub** [comment]
2) Fix. Thanks for the quick response

**Comment by bluesnowman** [comment]
@phpclub Are you porting up to 3.3 from 3.2?  DB_Connection::factory('default') is now DB_Connection_Driver::factory('default').  Is there a class in 3.3 that is referencing the old class name?  If so, I can update that as well for you.

**Comment by phpclub** [comment]
Yes. Thanx a lot
